- overrides/main.html
- overrides/partials/nav.html
> DOCS-87 Add pixel to all documentation sites.

- docs/db_provision.md
- docs/reference/copyright.md
- docs/release-notes/0.1.0.md
- docs/release-notes/index.md
- mkdocs-base.yml
- mkdocs.yml
Removing the section-index: {} plugin so that the 1st level in TOC has no content
Updating the 0.1.0 release notes
+ some minor fixes
> Removing the section-index: {} plugin + some minor fixes

- docs/index.md
- mkdocs-base.yml
Create a topic for Intrroduction to Percona Everest.
> everest-introduction

- docs/contribute.md
- docs/index.md
- docs/install/installEverest.md
- docs/install/uninstallEverest.md
- docs/quickstart-guide/eks.md
- docs/quickstart-guide/gke.md
- docs/quickstart-guide/qs-overview.md
- docs/quickstart-guide/qs-prerequisites.md
- docs/quickstart-guide/quick-install.md
- docs/use/backupRestore.md
- docs/use/cluster-management.md
- docs/use/scaling.md
- mkdocs-base.yml
modified:   docs/contribute.md
modified:   docs/index.md
modified:   docs/install/installEverest.md
modified:   docs/install/uninstallEverest.md
renamed:    docs/install/eks.md -> docs/quickstart-guide/eks.md
renamed:    docs/install/gke.md -> docs/quickstart-guide/gke.md
modified:   docs/quickstart-guide/qs-overview.md
modified:   docs/quickstart-guide/qs-prerequisites.md
modified:   docs/quickstart-guide/quick-install.md
modified:   docs/use/backupRestore.md
modified:   docs/use/cluster-management.md
modified:   docs/use/scaling.md
modified:   mkdocs-base.yml
> Fix links, TOC and QS section 

- docs/API.md
- mkdocs-base.yml
Add Everest API page:
https://docs.percona.com/everest-api-doc/
> Add API doc link

- mkdocs.yml
- overrides/main.html
modified:   mkdocs.yml
modified:   overrides/main.html
> Fix link in meta tag

- docs/migration_guide.md
- mkdocs-base.yml
Create a migration guide from PMM DBaaS to Percona Everest
> create migration guide for Everest

- docs/install/uninstallEverest.md
EVEREST-314
- Remove docker  compose
- Add removal of k8s resourcing blocking CRD removal
> EVEREST-314: uninstallation instructions for k8s

- snippets/services-banner.md
> Add the missing scarf pixel

- docs/quickstart-guide/quick-install.md
> Update quickinstall guide

- docs/install/installEverest.md
- docs/release-notes/Percona Everest 0.8.0 (2024-02-22).md
Add a note in the documentation that users cant upgrade to 0.8.0. To install v 0.8.0. they should first uninstalll the older version and then install v 0.8.0
> users cant uprgade to 0.8.0

- docs/install/installEverest.md
Add a note " Make sure to enter atleast one namespace while installing Percona Everest."
> add atleast one namespace

- docs/use/monitor_endpoints.md
Add the limitation to use HTTP and not HTTPS with self-signed certificates with PMM for monitoring.
> limitations add to monitoring

- docs/css/osano.css
- docs/js/consent.js
- mkdocs-base.yml
- overrides/main.html
- overrides/partials/copyright.html
- snippets/services-banner.md
new file:   docs/css/osano.css
new file:   docs/js/consent.js
modified:   mkdocs-base.yml
modified:   overrides/main.html
new file:   overrides/partials/copyright.html
modified:   snippets/services-banner.md
> DOCS-106 Implement Osano Cookie consent in docs.percona.com + remove scarf

- docs/install/installEverest.md
- docs/quickstart-guide/quick-install.md
- docs/release-notes/Percona Everest 0.9.1 (2024-04-02).md
- mkdocs-base.yml
Add release notes for Everest patch release 0.9.1
Update the Everest version in the documentation.
> Everest patch release 0.9.1

- docs/install/SetupPrereqs.md
- docs/quickstart-guide/gke.md
Update the Kubernetes version as the current version in the documentation is 1.25 which is outdated.
> Update Kubernetes version

- docs/use/createBackups/EnablePITR.md
- docs/use/db_provision.md
Add limitation for PITR and Retention copies For PG
> Limitations for PITR

- docs/release-notes/Percona-Everest-1.0.0-(2024-06-28).md
- docs/release-notes/release_notes_index.md
- mkdocs-base.yml
Create RN for 1.0.0
Update Index and Config file
> Release Notes 1.0

- docs/release-notes/Percona-Everest-1.0.1-(2024-07-08).md
- docs/release-notes/release_notes_index.md
- mkdocs-base.yml
Patch Release For Percona Everest to fix Telemetry issue
> Patch Release Percona Everest 1-0-1

- docs/index.md
> Update Percona Everest Docs

- docs/reference/known_limitations.md
- docs/release-notes/Percona-Everest-1.1.0-(2024-08-02).md
- docs/use/createBackups/CreateOnDemand.md
Add the limitations for PG:
https://perconadev.atlassian.net/browse/EVEREST-1213
> Pg limitations 1.1.0

- docs/install/SetupPrereqs.md
Add matrix to better help users on the many possible combinations.
Thanks
---
As it was before:
How it looks now:
> K8s distributions & K8s versions - matrix

- docs/use/API_rate_limit.md
Create a section to describe how to configure a session rate limit.
> Sessions Api rate limit

- docs/release-notes/Percona-Everest-1.1.1-(2024-08-25).md
- docs/release-notes/release_notes_index.md
- mkdocs-base.yml
Create release notes for patch release 1.1.1
> Release Notes 1.1.1

- docs/quickstart-guide/eks.md
- docs/quickstart-guide/gke.md
I've made a few small improvements and corrected the numbering of the instructions for clarity.
> Clarify documentation for Create Kubernetes cluster on Amazon Elastic Kubernetes Service (EKS)

- docs/administer/Idp_integration.md
> docs(Idp_integration.md): fix punctuation

- docs/css/design.css
> Fix the copy button getting merged in text in the code block

- docs/install/installEverestCLI.md
Fix for issue https://perconadev.atlassian.net/browse/EVEREST-1887
Please when merging, squash.
Thanks,
> EVEREST-1887 - fix CLI command

- docs/reference/known_limitations.md
For details, refer to the ticket:
https://perconadev.atlassian.net/browse/EVEREST-1368
> Pg backup files not deleted

- docs/install/installEverest.md
- docs/install/install_everest_helm_charts.md
- docs/quick-install.md
Remove the colon and add full stop for load balancer IP.
> remove colon as its confusing

- docs/install/install_everest_openshift.md
- mkdocs-base.yml
Create detailed documentation for the installation process of Percona Everest on OpenShift. Include step-by-step instructions, prerequisites, and configuration options.
> everest_openshift_installation

- docs/use/mongo_sharding.md
Refer to ticket:
https://perconadev.atlassian.net/browse/EVEREST-1915
> rename section Enable sharding in Percona Everest

- docs/upgrade/mongodb_major_upgrades.md
- mkdocs-base.yml
Create a section for major version upgrades of MongoDB.
> major_db_upgrades

- docs/install/install_everest_helm_charts.md
Add a detailed section that outlines the steps and procedures for deploying PMM (Percona Monitoring and Management) using Helm charts within the Percona Everest environment. 
Refer to the ticket: https://perconadev.atlassian.net/browse/EVEREST-1852
> helm-Support deploying PMM with Everest

- docs/reference/AI_disclaimer_for_docs.md
- mkdocs-base.yml
Include a disclaimer indicating the use of AI in our documentation.
> add_disclaimer _for_AI_use

- docs/upgrade/upgrade_with_cli.md
For detailed information, see the ticket:
https://perconadev.atlassian.net/browse/EVEREST-2103
> EVEREST-2103 bug for upgrade

- docs/release-notes/Percona-Everest-1.7.0-(2025-05-29).md
Fix the name of the PXC operator in RN 1.7.0.
> fix_operator_name_rn_1.7.0

- docs/get-help.md
Update the link to the community page for Percona Everest.
> fix_link_to_community_everest

- docs/security/sso_idp_integration.md
Fix the SSO page by adding the limitations for OIDC integration with Microsoft Entra
> Fix_SSO_page

- docs/release-notes/Percona-Everest-1.7.0-(2025-05-29).md
- docs/release-notes/Percona-Everest-1.8.0-(2025-07-16).md
- docs/release-notes/Percona-Everest-1.8.1-(2025-08-11).md
- docs/release-notes/release_notes_index.md
- mkdocs-base.yml
Patch Release 1.8.1 that fixes the following issue:
[EVEREST-2210](https://perconadev.atlassian.net/browse/EVEREST-2210)
> Patch Rel for Percona Everest 1.8.1
